name: Generate metrics

on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  metrics:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: unlsycn/metrics@master
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: soombrrg
          template: classic
          base: ""
          config_timezone: Europe/Minsk
          config_display: large
          config_animations: yes
          plugin_activity: yes
          plugin_activity_limit: 5
          plugin_activity_days: 14
          plugin_activity_filter: all
          plugin_habits: yes
          plugin_habits_from: 200
          plugin_habits_charts: yes
          plugin_habits_charts_type: radar
          filename: github-metrics.svg
          committer_token: ${{ secrets.GITHUB_TOKEN }}
